### ISSUE TITLE
[BUG] AntiXray doesn't work first time config file is created

### ISSUE THREAD

**Issue by Londiuh** [DrexHD/FabricAntiXray#1]
Anti-X-ray isn't enabled the first time you launch the server with this mod and the `./config/antixray.toml` file is created

**Comment by DrexHD** [comment]
I am unable to reproduce this issue and looking through the code it shouldn't happen, because of this null check: [WorldConfig.java#L23](https://github.com/DrexHD/FabricAntiXray/blob/master/src/main/java/me/drex/antixray/config/WorldConfig.java#L23)

**Comment by Londiuh** [comment]
Weird. I tried again and I can reproduce the bug. When the `loadConfig()` method is called, [Config.java#L13](https://github.com/DrexHD/FabricAntiXray/blob/master/src/main/java/me/drex/antixray/config/Config.java#L13) only gets a value assigned if `./config/antixray.toml` exists, else only creates `./config/antixray.toml` and assigns nothing to [Config.java#L13](https://github.com/DrexHD/FabricAntiXray/blob/master/src/main/java/me/drex/antixray/config/Config.java#L13) (so it's null). This doesn't happen for me with #2.

**Comment by DrexHD** [comment]
Ok, I did some more testing and was able to reproduce it.
