### ISSUE TITLE
Is there a chance of a 1.16.5 version?

### ISSUE THREAD

**Issue by OsoaGitHub** [DrexHD/FabricAntiXray#3]

**Comment by DrexHD** [comment]
I will look into it and backport it to 1.16.5 if it isn't too much work.

**Comment by DrexHD** [comment]
Initial backport for [1.16.5](https://github.com/DrexHD/FabricAntiXray/tree/1.16.5) done! You can download the [artifacts](https://github.com/DrexHD/FabricAntiXray/suites/3495870056/artifacts/83265928) to test it out. Do note though that I have barely tested this build and it might still contain bugs! It would be awesome if you could give this repository a star!
